[package]
name = "rload"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
bytes = "1.9.0"
clap = { version = "4.5.23", features = ["derive", "env"] }
h2 = { version = "0.4.7", features = ["stream"] }
http = "1.2.0"
httparse = "1.9.5"
human_bytes = "0.4.3"
num_cpus = "1.16.0"
pin-project = "1.1.7"
regex_static = "0.1.1"
rustls = "0.23.19"
tokio = { version = "1.42.0", features = ["full"] }
tokio-rustls = "0.26.1"
url = "2.5.4"
