[profile.release]
opt-level = 3
debug = false
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = false
strip = "symbols"
incremental = false
debug-assertions = false

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=native"]

# [unstable]
# build-std = ["core", "alloc", "std", "panic_abort"]